server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: journal-service
              uri: lb://journal-service-dev
              predicates:
                - Path=/api/v1/*/journal/**, /api/v1/*/users/**

    kubernetes:
      discovery:
        enabled: true
        all-namespaces: false
      loadbalancer:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
